/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardsView: typeof import('./src/components/CardsView.vue')['default']
    CardTemplate: typeof import('./src/components/CardTemplate.vue')['default']
    ChoseThemeView: typeof import('./src/components/ChoseThemeView.vue')['default']
    MainFrame: typeof import('./src/components/MainFrame.vue')['default']
    NavbarView: typeof import('./src/components/NavbarView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeIcons: typeof import('./src/components/icons/ThemeIcons.vue')['default']
    WindowControl: typeof import('./src/components/window/WindowControl.vue')['default']
  }
}
