/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardImg: typeof import('bootstrap-vue-next/components/BCard')['BCardImg']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    CardsView: typeof import('./src/components/CardsView.vue')['default']
    CardTemplate: typeof import('./src/components/CardTemplate.vue')['default']
    ChoseThemeView: typeof import('./src/components/ChoseThemeView.vue')['default']
    MainFrame: typeof import('./src/components/MainFrame.vue')['default']
    NavbarView: typeof import('./src/components/NavbarView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeIcons: typeof import('./src/components/icons/ThemeIcons.vue')['default']
    WindowControl: typeof import('./src/components/window/WindowControl.vue')['default']
  }
}
